# This file describes the configuration for the molecular dynamics simulation.
# Comments are added to explain the role of each parameter.

##############################################################################################
#                                     Simulation Setup                                       #
##############################################################################################

# The absolute path to the directory where simulation output files (.dump) will be saved.
simulation_directory: "simulations"

# The size of the cubic simulation box in Angstroms.
simulation_box_size: 40

# The total number of water molecules to be simulated.
number_water_molecules: 40

# The time step for the Verlet integration in picoseconds.
time_step: 0.0002

# The total number of steps to run the simulation for.
simulation_steps: 100000

##############################################################################################
#                                     Physical Constants                                     #
##############################################################################################

# The Boltzmann constant in the simulation's unit system.
# Units : [A^2] [Da] [picoseconds-2] [K-1]
boltzman_constant: 0.8314654859720001

# The Coulomb's constant for calculating electrostatic forces in the simulation's unit system.
# electrostatic constant in Daltons, electron charges, picosecond, angstrom units
coulombs_constant: 138938.66759164268

##############################################################################################
#                                   Force Field Parameters                                   #
##############################################################################################

# Parameters for the Lennard-Jones potential, modeling non-bonded interactions.
lennard_jones_parameters:
    # Epsilon: The depth of the potential well (in simulation energy units).
    epsilon:
        oxygen_oxygen: 62.87
        oxygen_hydrogen: 14.2723
        hydrogen_hydrogen: 3.24
    # Sigma: The finite distance at which the inter-particle potential is zero (in Angstroms).
    sigma:
        oxygen_oxygen: 3.1169
        oxygen_hydrogen: 2.04845
        hydrogen_hydrogen: 0.98

# Parameters specific to the TIP3P/F water model.
water_configurations:
    # The equilibrium bond length between Oxygen and Hydrogen atoms in Angstroms.
    bond_length: 0.9572
    # The spring constant for the bond stretching potential.
    bond_spring_constant: 450000.0
    # The equilibrium angle for H-O-H in radians.
    water_angle: 1.8229964037080773
    # The spring constant for the angle bending potential.
    angle_spring_constant: 3530000.0

############################################################################################
#                                  Particle Initialization                                 #
############################################################################################

# Defines the mass for each type of atom in atomic mass units.
mass_configurations:
    hydrogen: 1
    nitrogen: 14
    carbon: 12
    oxygen: 16

# Maps atom types to integer IDs for use in simulation arrays and output files.
particle_type_configurations:
    hydrogen: 0
    oxygen: 1
    carbon: 2
    nitrogen: 3

# Parameters controlling the initial placement of molecules in the simulation box.
position_initiation_configurations:
    # The maximum occupancy of the simulation box to avoid starting with overlapping particles.
    max_occupancy: 0.95
    # The initial offset for placing hydrogen atoms around an oxygen atom.
    initial_hydrogen_offset: 1
    # The number of attempts to find a non-overlapping position for a new molecule.
    distance_maximization_steps: 50
    # The minimum desired distance between the oxygen atoms of different molecules at initialization.
    minimum_desired_distance: 3